# INFORMACIÓN DEL PROYECTO

### TÍTULO

In [ ]:
#Escribe el título del proyecto en Markdown
titulo = "Chess Opening Evaluator"

### TEMA

# Describe brevemente el tema del proyecto en Markdown
Este proyecto desarrolla un sistema de Machine Learning diseñado para analizar, clasificar y recomendar aperturas de ajedrez personalizadas. A diferencia de los motores de búsqueda tradicionales, el sistema utiliza algoritmos de aprendizaje no supervisado (Clustering) y aprendizaje basado en instancias (KNN) para identificar patrones de juego y similitudes entre posiciones teóricas y partidas reales.

### OBJETIVOS

Define aquí el objetivo del proyecto

Proporcionar al jugador un repertorio inteligente basado en datos, que no solo sugiera qué jugar según la teoría, sino que se adapte a su estilo y rendimiento mediante el análisis de sus propias partidas y sugerencias personalizadas para trabajar los errores.

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [ ]:
# API DE LICHESS Y WEB SCRAPING (MODERN-CHESS,YOUTUBE,LIBROS INTERNET)

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Proyectos\Proyecto ML\master_dataset_ml.csv")
df2 = pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Proyectos\Proyecto ML\src_manual.csv")
df3 = pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Proyectos\Proyecto ML\src_modern_chess.csv")
df4 = pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Proyectos\Proyecto ML\src_youtube.csv")

In [3]:
df1.head()

,Usuario,Rating_Usuario,Apertura,Color,Fin_Teoria,ACL_Post_Teo,Victoria,Game_ID
0,stevobrine,1833,Philidor Defense,Blancas,7,219.0,0.0,NaN
1,tecojoytetruqueo,2360,Caro-Kann Defense,Blancas,15,136.0,1.0,JeARD20g
2,tecojoytetruqueo,2360,Petrov's Defense,Blancas,17,73.0,0.0,RaSGXBJe
3,tecojoytetruqueo,2360,Queen's Pawn Game,Negras,9,129.3,0.0,DH2yl6ve
4,tecojoytetruqueo,2360,King's Indian Attack,Negras,15,4.0,1.0,5i9zdJLz

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2854 entries, 0 to 2853
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Usuario         2854 non-null   object
 1   Rating_Usuario  2854 non-null   int64
 2   Apertura        2854 non-null   object
 3   Color           2854 non-null   object
 4   Fin_Teoria      2854 non-null   int64
 5   ACL_Post_Teo    2854 non-null   float64
 6   Victoria        2854 non-null   float64
 7   Game_ID         2853 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 178.5+ KB

In [5]:
df2.head()

,resource_id,source,title,url,resource_type,format,course_type,openings,color,author,...,has_video,has_pgn,has_exercises,has_spaced_rep,rating_score,n_reviews,views_yt,pub_date,description,tags
0,man__my_system,manual,My System,https://www.amazon.com/s?k=My+System+Nimzowitsch,book,text,middlegame,NaN,Both,Nimzowitsch,...,0,0,0,0,NaN,NaN,NaN,NaN,"Fundamental positional chess: blockade, prophy...",NaN
1,man__chess_fundamentals,manual,Chess Fundamentals,https://www.gutenberg.org/ebooks/33370,book,text,general,NaN,Both,Capablanca,...,0,0,0,0,NaN,NaN,NaN,NaN,Essential principles for beginners. Free on Pr...,NaN
2,man__dvoretsky_s_endgame_manual,manual,Dvoretsky's Endgame Manual,https://www.amazon.com/s?k=Dvoretsky+Endgame+M...,book,text,endgame,NaN,Both,Dvoretsky,...,0,0,1,0,NaN,NaN,NaN,NaN,Definitive endgame reference for advanced and ...,NaN
3,man__silman_s_complete_endgame_course,manual,Silman's Complete Endgame Course,https://www.amazon.com/s?k=Silman+Complete+End...,book,text,endgame,NaN,Both,Silman,...,0,0,1,0,NaN,NaN,NaN,NaN,Endgame curriculum organized by rating level f...,NaN
4,man__winning_chess_tactics,manual,Winning Chess Tactics,https://www.amazon.com/s?k=Winning+Chess+Tacti...,book,text,tactics,NaN,Both,Seirawan,...,0,0,1,0,NaN,NaN,NaN,NaN,"Systematic introduction to forks, pins, skewer...",NaN

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resource_id     13 non-null     object
 1   source          13 non-null     object
 2   title           13 non-null     object
 3   url             13 non-null     object
 4   resource_type   13 non-null     object
 5   format          13 non-null     object
 6   course_type     13 non-null     object
 7   openings        2 non-null      object
 8   color           13 non-null     object
 9   author          13 non-null     object
 10  author_title    0 non-null      float64
 11  level_min       13 non-null     int64
 12  level_max       13 non-null     int64
 13  level_tier      13 non-null     object
 14  duration_min    0 non-null      float64
 15  price_eur       13 non-null     float64
 16  is_free         13 non-null     int64
 17  has_video       13 non-null     int64
 18  has_pgn         13 non-null     int64
 19  has_exercises   13 non-null     int64
 20  has_spaced_rep  13 non-null     int64
 21  rating_score    0 non-null      float64
 22  n_reviews       0 non-null      float64
 23  views_yt        0 non-null      float64
 24  pub_date        0 non-null      float64
 25  description     13 non-null     object
 26  tags            0 non-null      float64
dtypes: float64(8), int64(7), object(12)
memory usage: 2.9+ KB

In [7]:
df3.head()

,resource_id,source,title,url,resource_type,format,course_type,openings,color,author,...,has_video,has_pgn,has_exercises,has_spaced_rep,rating_score,n_reviews,views_yt,pub_date,description,tags
0,mc__chebanenko_slav_for_black_part_1,modern_chess,Chebanenko Slav for Black - Part 1,https://www.modern-chess.com/course/chebanenko...,course,video,opening,Slav Defense|1.d4,Black,"GMPier Luigi Basso, GMVladimir Malakhov",...,1,1,1,1,NaN,NaN,NaN,NaN,"May 3, 2026Slav Defense1.d4",NaN
1,mc__inside_your_games_edition_4,modern_chess,Inside Your Games - Edition 4Discounted,https://www.modern-chess.com/course/inside-you...,course,video,general,NaN,Both,GMIoannis Papaioannou,...,1,1,1,0,NaN,NaN,NaN,NaN,The fourth installment of GM Ioannis Papaioann...,NaN
2,mc__1_d4_nf6_2_nf3_g6_3_nbd2_deep_understand,modern_chess,1.d4 Nf6 2.Nf3 g6 3.Nbd2 - Deep UnderstandingD...,https://www.modern-chess.com/course/1-d4-nf6-2...,course,video,opening,King%27s Indian Defense|Gruenfeld Defense|Pirc...,Both,GMIoannis Papaioannou,...,1,1,0,0,NaN,NaN,NaN,NaN,GM Ioannis Papaioannou presents a complete Whi...,NaN
3,mc__french_steinitz_with_rb8_repertoire_for_,modern_chess,French Steinitz with ...Rb8 - Repertoire for B...,https://www.modern-chess.com/course/french-ste...,course,video,opening,French Defense|1.e4,Black,"GMPier Luigi Basso, GMSzymon Gumularz",...,1,1,1,1,NaN,NaN,NaN,NaN,"May 1, 2026French Defense1.e4",NaN
4,mc__kings_indian_defense_repertoire_for_blac,modern_chess,King's Indian Defense: Repertoire for Black - ...,https://www.modern-chess.com/course/kings-indi...,course,video,opening,King%27s Indian Defense,Black,"GMAndrea Stella, GMBaadur Jobava",...,1,1,1,1,NaN,NaN,NaN,NaN,"April 30, 2026King's Indian Defense",NaN

In [8]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resource_id     825 non-null    object
 1   source          825 non-null    object
 2   title           825 non-null    object
 3   url             825 non-null    object
 4   resource_type   825 non-null    object
 5   format          825 non-null    object
 6   course_type     825 non-null    object
 7   openings        654 non-null    object
 8   color           825 non-null    object
 9   author          825 non-null    object
 10  author_title    772 non-null    object
 11  level_min       825 non-null    int64
 12  level_max       825 non-null    int64
 13  level_tier      825 non-null    object
 14  duration_min    572 non-null    float64
 15  price_eur       0 non-null      float64
 16  is_free         825 non-null    int64
 17  has_video       825 non-null    int64
 18  has_pgn         825 non-null    int64
 19  has_exercises   825 non-null    int64
 20  has_spaced_rep  825 non-null    int64
 21  rating_score    0 non-null      float64
 22  n_reviews       0 non-null      float64
 23  views_yt        0 non-null      float64
 24  pub_date        0 non-null      float64
 25  description     825 non-null    object
 26  tags            0 non-null      float64
dtypes: float64(7), int64(7), object(13)
memory usage: 174.2+ KB

In [9]:
df4.head()

,resource_id,source,title,url,resource_type,format,course_type,openings,color,author,...,has_video,has_pgn,has_exercises,has_spaced_rep,rating_score,n_reviews,views_yt,pub_date,description,tags
0,yt__qm4e7g2ruki,youtube,The Sicilian Defense | 10-Minute Chess Openings,https://www.youtube.com/watch?v=qM4e7g2RukI,video,video,opening,Sicilian Defense,Black,GothamChess,...,1,NaN,NaN,NaN,NaN,NaN,3500487,2020-06-11,➡️ Get My Chess Courses: https://www.chessly....,NaN
1,yt__0iayykxh3zc,youtube,DOMINATE as Black with the Sicilian Defense,https://www.youtube.com/watch?v=0iAyyKxh3zc,video,video,opening,Sicilian Defense,Black,ChessPage1,...,1,NaN,NaN,NaN,NaN,NaN,702588,2025-07-26,Try chessreps for FREE using my link so they k...,NaN
2,yt__2miollk8dii,youtube,Sicilian Defense ALL Variations Explained in 1...,https://www.youtube.com/watch?v=2miolLK8DiI,video,video,opening,Sicilian Defense,Black,Remote Chess Academy,...,1,NaN,NaN,NaN,NaN,NaN,778359,2024-01-26,Learn 3 Simple Rules To Reach 2000+ ELO Rating...,NaN
3,yt__6msbe_cahf4,youtube,BEST Chess Opening for Black: Sicilian Defense...,https://www.youtube.com/watch?v=6msbe_CAhf4,video,video,opening,Sicilian Defense,Black,Chess Talk,...,1,NaN,NaN,NaN,NaN,NaN,2293833,2018-03-03,Find out the Best Chess Opening Strategy for B...,NaN
4,yt__n2vdfnrwrfa,youtube,HOW TO PLAY SICILIAN DEFENSE! Opening explained,https://www.youtube.com/watch?v=n2vdFNrWrFA,video,video,opening,Sicilian Defense,Black,Biyaherong Chess Coach,...,1,NaN,NaN,NaN,NaN,NaN,136865,2022-09-13,For more videos\nWesley So Notable Game\nhttps...,NaN

In [10]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resource_id     80 non-null     object
 1   source          80 non-null     object
 2   title           80 non-null     object
 3   url             80 non-null     object
 4   resource_type   80 non-null     object
 5   format          80 non-null     object
 6   course_type     80 non-null     object
 7   openings        80 non-null     object
 8   color           80 non-null     object
 9   author          80 non-null     object
 10  author_title    0 non-null      float64
 11  level_min       80 non-null     int64
 12  level_max       80 non-null     int64
 13  level_tier      80 non-null     object
 14  duration_min    0 non-null      float64
 15  price_eur       80 non-null     float64
 16  is_free         80 non-null     int64
 17  has_video       80 non-null     int64
 18  has_pgn         0 non-null      float64
 19  has_exercises   0 non-null      float64
 20  has_spaced_rep  0 non-null      float64
 21  rating_score    0 non-null      float64
 22  n_reviews       0 non-null      float64
 23  views_yt        80 non-null     int64
 24  pub_date        80 non-null     object
 25  description     80 non-null     object
 26  tags            0 non-null      float64
dtypes: float64(9), int64(5), object(13)
memory usage: 17.0+ KB